server:
  port: 9095

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri:
            lb://PRODUCT-SERVICE
          predicates:
          - Path=/product/**

        - id: REVIEW-SERVICE
          uri:
            lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**



